app:
  name: "web_app"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  min_age: 30
  max_backups: 7
mysql:
  host: "127.9.9.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "web_app"
  mysql.max_open_conns: 200
  mysql.max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port:
  db: 0
  password: ""
  pool_size: 100